### ISSUE TITLE
Error in step09: infer presence/absence and gain/loss patterns of all genes

### ISSUE THREAD

**Issue by johanneswerner** [neherlab/pan-genome-analysis#10]
I am running `panX` on 63 genomes (6 complete, 57 draft genomes). 

The `raxml.log` shows me that RAxML finishes succesfully but 8 identical sequences have been found. I attached the terminal output for step09 below. 

Any ideas? Thank you very much.

```
======  starting step09: infer presence/absence and gain/loss patterns of all genes

0.00    -TreeAnc: set-up

0.06    -TreeAnc: loading alignment failed... 

0.06    -TreeAnc.infer_ancestral_sequences with method: ml, joint

0.06    TreeAnc.infer_ancestral_sequences: ERROR, alignment or tree are missing
Traceback (most recent call last):
  File "./panX.py", line 312, in <module>
    myPangenome.infer_gene_gain_loss_pattern()
  File "/data/tools/pan-genome-analysis/scripts/pangenome_computation.py", line 214, in infer_gene_gain_loss_pattern
    process_gain_loss(self.path, self.merged_gain_loss_output)
  File "/data/tools/pan-genome-analysis/scripts/sf_gain_loss.py", line 102, in process_gain_loss
    tree = infer_gene_gain_loss(path)
  File "/data/tools/pan-genome-analysis/scripts/sf_gain_loss.py", line 40, in infer_gene_gain_loss
    n.genepresence = n.sequence
AttributeError: 'Clade' object has no attribute 'sequence'
```

**Comment by rneher** [comment]
could it be that there are '-' or other special characters in your file names. We have had this error with '-' in file or strain names.

**Comment by johanneswerner** [comment]
Yes, that was the problem. Thank you for helping out.
