### ISSUE TITLE
Newick

### ISSUE THREAD

**Issue by mdieser** [neherlab/pan-genome-analysis#18]
Hi - I'm running into an error during step 8. Please see output below. Any suggestions how to fix this error? 
 Best wishes,

Markus

======  starting step08: run fasttree and raxml for tree construction
 fasttree time-cost:  0.00 minutes (0.01 seconds)
Traceback (most recent call last):
  File "./panX.py", line 303, in <module>
    myPangenome.build_core_tree()
  File "/media/LargeStorage/Markus_cold_adaptation-master/pangenomeanalysis/pan-genome-analysis/scripts/pangenome_computation.py", line 200, in build_core_tree
    aln_to_Newick(self.path, self.folders_dict, self.raxml_max_time, self.raxml_path, self.threads)
  File "/media/LargeStorage/Markus_cold_adaptation-master/pangenomeanalysis/pan-genome-analysis/scripts/sf_core_tree_build.py", line 44, in aln_to_Newick
    resolve_polytomies('initial_tree.newick0','initial_tree.newick')
  File "/media/LargeStorage/Markus_cold_adaptation-master/pangenomeanalysis/pan-genome-analysis/scripts/sf_core_tree_build.py", line 8, in resolve_polytomies
    tree = Tree(newickString);
  File "/home/markusd/.local/lib/python2.7/site-packages/ete2/coretype/tree.py", line 218, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/home/markusd/.local/lib/python2.7/site-packages/ete2/parser/newick.py", line 231, in read_newick
    raise NewickError('Unexisting tree file or Malformed newick tree structure.')
ete2.parser.newick.NewickError: Unexisting tree file or Malformed newick tree structure.

**Comment by rneher** [comment]
this is probably an error in tree building. In the past, this has been caused by non-standard characters in strain names or too diverse data set without a core genome.

**Comment by mdieser** [comment]
Could the version of ete2 be a case for this error?

**Comment by mdieser** [comment]
I'm referring to ete2 or ete3...

**Comment by mdieser** [comment]
Your initial suggestion was correct. I did not find obvious differences between files but after adding one file at the time to the pipeline, I discovered five compromised .gbk. Analysis runs fine without these files. Thanks again for your support!

**Comment by rneher** [comment]
good to hear and sorry about the hassle. I know we need to work on error messages and sanity checks...

**Comment by mdieser** [comment]
No worries, We all are busy and sometime it takes days or weeks to respond. 
Also realized the other day that the requirements.txt file you provided would have answered my questions about the version of ete. So, i have to apologize for not doing my homework first :)

**Comment by jimnoneill** [comment]
Hi. Get this same errror while running the test data set. I am using Linux Mint 19.3 Cinnamon, and running from an anaconda python2 environment.
