### ISSUE TITLE
Error step 10

### ISSUE THREAD

**Issue by mdieser** [neherlab/pan-genome-analysis#19]
Hello again - Any explanation what may cause an issue with certain files in the genecluster folder?
Thanks,
Markus

Starting step10: create json file for geneDataTable visualization
Traceback (most recent call last):
  File "./panX.py", line 322, in <module>
    myPangenome.export_geneCluster_json()
  File "/software/pangenomeanalysis/pan-genome-analysis/scripts/pangenome_computation.py", line 225, in export_geneCluster_json
    geneCluster_to_json(self.path, self.enable_RNA_clustering, self.store_locus_tag, self.raw_locus_tag, self.optional_table_column)
  File "/software/pangenomeanalysis/pan-genome-analysis/scripts/sf_geneCluster_json.py", line 171, in geneCluster_to_json
    '"divers":"'+gene_diversity_Dt[clusterID]+'"',
KeyError: 'GC00000193_3'

**Comment by rneher** [comment]
Did you run this of a clean directory, or could there have been geneCluster files in the folder from a previous run?

**Comment by mdieser** [comment]
Thank you. That solved the problem. 
Markus
