### ISSUE TITLE
Running sh run-TestSet.sh cause error

### ISSUE THREAD

**Issue by OlegKotcar** [neherlab/pan-genome-analysis#31]
(panX) anna@Anna-PC:~/work/pan-genome-analysis$ sudo sh run-TestSet.sh
Traceback (most recent call last):
  File "./panX.py", line 6, in <module>
    from pangenome_computation import pangenome
  File "/home/anna/work/pan-genome-analysis/scripts/pangenome_computation.py", line 16, in <module>
    from sf_gain_loss import process_gain_loss
  File "/home/anna/work/pan-genome-analysis/scripts/sf_gain_loss.py", line 5, in <module>
    from treetime import TreeAnc
  File "build/bdist.linux-x86_64/egg/treetime/__init__.py", line 4, in <module>
ImportError: cannot import name item

**Comment by rneher** [comment]
If you run `from treetime import TreeAnc` in your python interpreter, does it work? Try updating TreeTime from pypi.

**Comment by OlegKotcar** [comment]
No it didn't work.

(base) anna@Anna-PC:~/work$ pip3 install Treetime
Collecting Treetime
  Cache entry deserialization failed, entry ignored
Installing collected packages: Treetime
Successfully installed Treetime-2018.10

(base) anna@Anna-PC:~/work$ cat ./test.py 
from Treetime import TreeAnc

(base) anna@Anna-PC:~/work$ python ./test.py 
Traceback (most recent call last):
  File "./test.py", line 1, in <module>
    from Treetime import TreeAnc
ModuleNotFoundError: No module named 'Treetime'

**Comment by rneher** [comment]
the treetime you want is phylo-treetime

pip install phylo-treetime
