### ISSUE TITLE
Failed to run Test

### ISSUE THREAD

**Issue by stheil15** [neherlab/pan-genome-analysis#34]
Hi,
I have used PanX successfully a few month ago. Now that i have migrated on ubuntu 18.04, i tried to reinstall it via git clone then conda install, but i failed to run the test... Here is the error message :

```
mv: impossible d'évaluer 'GC00000142_aa_aln.fa': Aucun fichier ou dossier de ce type
mv: impossible d'évaluer 'GC00000142_na_aln.fa': Aucun fichier ou dossier de ce type
mv: impossible d'évaluer 'GC00000364_aa_aln.fa': Aucun fichier ou dossier de ce type
mv: impossible d'évaluer 'GC00000364_na_aln.fa': Aucun fichier ou dossier de ce type
mv: impossible d'évaluer 'GC00000322_aa_aln.fa': Aucun fichier ou dossier de ce type
mv: impossible d'évaluer 'GC00000322_na_aln.fa': Aucun fichier ou dossier de ce type
mv: impossible d'évaluer 'GC00000172_aa_aln.fa': Aucun fichier ou dossier de ce type
mv: impossible d'évaluer 'GC00000172_na_aln.fa': Aucun fichier ou dossier de ce type
mv: impossible d'évaluer 'GC00000217_aa_aln.fa': Aucun fichier ou dossier de ce type
mv: impossible d'évaluer 'GC00000217_na_aln.fa': Aucun fichier ou dossier de ce type
Traceback (most recent call last):
  File "./panX.py", line 303, in <module>
    myPangenome.build_core_tree()
  File "/home/stheil/soft/pan-genome-analysis/scripts/pangenome_computation.py", line 200, in build_core_tree
    aln_to_Newick(self.path, self.folders_dict, self.raxml_max_time, self.raxml_path, self.threads)
  File "/home/stheil/soft/pan-genome-analysis/scripts/sf_core_tree_build.py", line 44, in aln_to_Newick
    resolve_polytomies('initial_tree.newick0','initial_tree.newick')
  File "/home/stheil/soft/pan-genome-analysis/scripts/sf_core_tree_build.py", line 8, in resolve_polytomies
    tree = Tree(newickString);
  File "/home/stheil/anaconda3/envs/panX/lib/python2.7/site-packages/ete2/coretype/tree.py", line 218, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/home/stheil/anaconda3/envs/panX/lib/python2.7/site-packages/ete2/parser/newick.py", line 231, in read_newick
    raise NewickError('Unexisting tree file or Malformed newick tree structure.')
ete2.parser.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
```
If any idea where to start to debug, it would be much appreciated ;)
Thanks

Seb

**Comment by Laura-Alex** [comment]
Just wanted to note that I got exactly the same bug. Help would be appreciated.

**Comment by stheil15** [comment]
Seems to be an library path or a program binary missing, but don't know which one...
I've tried it on a fresh Ubuntu install and it worked !

**Comment by jimnoneill** [comment]
I've run into this same issue on Linux Mint 19.3. An tips for detective work on how to find the missing binaries?
Update: The binaries I found did not work.

**Comment by jimnoneill** [comment]
Now I'm left with a new error:
Traceback (most recent call last):
  File "./panX.py", line 287, in <module>
    myPangenome.process_clusters()
  File "/home/jme/pan-genome-analysis/scripts/pangenome_computation.py", line 180, in process_clusters
    myClusterCollector.estimate_raw_core_diversity()
  File "/home/jme/pan-genome-analysis/scripts/cluster_collective_processing.py", line 17, in estimate_raw_core_diversity
    self.folders_dict, self.strain_list, self.threads, self.core_genome_threshold, self.factor_core_diversity, self.species)
  File "/home/jme/pan-genome-analysis/scripts/sf_core_diversity.py", line 102, in estimate_core_gene_diversity
    calculated_core_diversity=tmp_average_core_diversity(tmp_core_seq_path)
  File "/home/jme/pan-genome-analysis/scripts/sf_core_diversity.py", line 43, in tmp_average_core_diversity
    diversity_lst=[float(iline.split('\t')[1]) for iline in tmp_core_diversity_file]
ValueError: invalid literal for float(): 0GC00000031.fna
