### ISSUE TITLE
step 11: ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by NA1919** [neherlab/pan-genome-analysis#44]
hello,

I am running panX with branch associations. I have a metadata.tsv file and a descriptive metainfo.tsv file.
I keep getting this error on step 11: 

/beegfs/work/workspace/ws/fr_na50-panx-0/pan-genome-analysis/scripts/sf_association.py:188: RuntimeWarning: divide by zero encountered in divide
  *((root_node.meta_sq_value - n.meta_sq_value)/n_non_child
/beegfs/work/workspace/ws/fr_na50-panx-0/pan-genome-analysis/scripts/sf_association.py:189: RuntimeWarning: invalid value encountered in double_scalars
  - n.meta_ancestral_average**2)
/beegfs/work/workspace/ws/fr_na50-panx-0/pan-genome-analysis/scripts/sf_association.py:200: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(n.meta_ancestral_SSEM + n.meta_derived_SSEM)
/beegfs/work/workspace/ws/fr_na50-panx-0/pan-genome-analysis/scripts/sf_association.py:272: RuntimeWarning: invalid value encountered in absolute
  association_dict[clusterID][d["meta_category"]] = np.abs(score)
Traceback (most recent call last):
  File "./panX.py", line 329, in <module>
    myPangenome.export_coreTree_json()
  File "/beegfs/work/workspace/ws/fr_na50-panx-0/pan-genome-analysis/scripts/pangenome_computation.py", line 229, in export_coreTree_json
    json_parser(self.path, self.folders_dict, self.fpaths_dict, self.metainfo_fpath, self.meta_data_config, self.clean_temporary_files)
  File "/beegfs/work/workspace/ws/fr_na50-panx-0/pan-genome-analysis/scripts/sf_coreTree_json.py", line 264, in json_parser
    process_metajson(path, meta_data_config, metajson_dict)
  File "/beegfs/work/workspace/ws/fr_na50-panx-0/pan-genome-analysis/scripts/sf_coreTree_json.py", line 173, in process_metajson
    meta_category, data_type, display, associate= iline.rstrip().split('\t')[:4]
ValueError: need more than 1 value to unpack

thank you in advance for any help
Nurper

**Comment by pvdam3** [comment]
I encountered this issue today as well, and was able to trace it back to the meta_config.tsv file, which had one or two empty lines at the end. Upon removing these, the script ran through completely without errors. Hope this still helps someone attempting to get panX to run.
