### ISSUE TITLE
Failed to export myPangenome's geneCluster.json (step 10)

### ISSUE THREAD

**Issue by jhcuarta** [neherlab/pan-genome-analysis#51]
Hi
I encounter an error while running the next command line
./panX.py -fn ./data/Vibrio_complete -sl Vibrio_complete -dmdc -t 1 > Vibrio_complete.log

The error follows as

Traceback (most recent call last):
  File "./panX.py", line 322, in <module>
    myPangenome.export_geneCluster_json()
  File "/home/jason/Documents/pan-genome-analysis/scripts/pangenome_computation.py", line 225, in export_geneCluster_json
    geneCluster_to_json(self.path, self.enable_RNA_clustering, self.store_locus_tag, self.raw_locus_tag, self.optional_table_column)
  File "/home/jason/Documents/pan-genome-analysis/scripts/sf_geneCluster_json.py", line 171, in geneCluster_to_json
    '"divers":"'+gene_diversity_Dt[clusterID]+'"',
KeyError: 'GC00002056'

**Comment by ValeC08** [comment]
Hello,

I got the same error running panX on my genomes, in my case Mycobacterial genome. 
Did you have any guess of what was the problem?

Thank you,

Valentina
